/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ai;

/**
 *
 * @author ASUS
 */
public class NewJFrame extends javax.swing.JFrame {
    Puzzle puz;
    int[][] process;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        sl00 = new javax.swing.JLabel();
        sl10 = new javax.swing.JLabel();
        sl01 = new javax.swing.JLabel();
        sl11 = new javax.swing.JLabel();
        tl01 = new javax.swing.JLabel();
        tl10 = new javax.swing.JLabel();
        tl11 = new javax.swing.JLabel();
        tl00 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tl02 = new javax.swing.JLabel();
        tl12 = new javax.swing.JLabel();
        tl21 = new javax.swing.JLabel();
        tl20 = new javax.swing.JLabel();
        tl22 = new javax.swing.JLabel();
        sl20 = new javax.swing.JLabel();
        sl21 = new javax.swing.JLabel();
        sl02 = new javax.swing.JLabel();
        sl12 = new javax.swing.JLabel();
        sl22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        upb = new javax.swing.JButton();
        startb = new javax.swing.JButton();
        leftb = new javax.swing.JButton();
        downb = new javax.swing.JButton();
        endb = new javax.swing.JButton();
        rightb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Target");

        sl00.setText("0");

        sl10.setText("0");

        sl01.setText("0");

        sl11.setText("0");

        tl01.setText("0");

        tl10.setText("0");

        tl11.setText("0");

        tl00.setText("0");

        jLabel10.setText("Puzzle");

        tl02.setText("0");

        tl12.setText("0");

        tl21.setText("0");

        tl20.setText("0");

        tl22.setText("0");

        sl20.setText("0");

        sl21.setText("0");

        sl02.setText("0");

        sl12.setText("0");

        sl22.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tl10)
                                .addGap(18, 18, 18)
                                .addComponent(tl11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tl12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tl00)
                                .addGap(18, 18, 18)
                                .addComponent(tl01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tl02))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tl20)
                                .addGap(18, 18, 18)
                                .addComponent(tl21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tl22))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sl10)
                                .addGap(18, 18, 18)
                                .addComponent(sl11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sl12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sl00)
                                .addGap(18, 18, 18)
                                .addComponent(sl01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sl02))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sl20)
                                .addGap(18, 18, 18)
                                .addComponent(sl21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sl22)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sl00)
                    .addComponent(sl01)
                    .addComponent(sl02))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sl10)
                    .addComponent(sl11)
                    .addComponent(sl12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sl20)
                    .addComponent(sl21)
                    .addComponent(sl22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tl01)
                    .addComponent(tl00)
                    .addComponent(tl02))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tl10)
                    .addComponent(tl11)
                    .addComponent(tl12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tl20)
                    .addComponent(tl21)
                    .addComponent(tl22))
                .addContainerGap())
        );

        upb.setText("Up");
        upb.setEnabled(false);
        upb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upbMouseClicked(evt);
            }
        });

        startb.setText("Start");
        startb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startbMouseClicked(evt);
            }
        });
        startb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbActionPerformed(evt);
            }
        });

        leftb.setText("Left");
        leftb.setEnabled(false);
        leftb.setPreferredSize(new java.awt.Dimension(69, 29));
        leftb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftbMouseClicked(evt);
            }
        });

        downb.setText("Down");
        downb.setEnabled(false);
        downb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downbMouseClicked(evt);
            }
        });
        downb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downbActionPerformed(evt);
            }
        });

        endb.setText("End");
        endb.setEnabled(false);
        endb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endbMouseClicked(evt);
            }
        });

        rightb.setText("Right");
        rightb.setEnabled(false);
        rightb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(startb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(endb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(leftb, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(downb, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightb, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leftb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rightb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(upb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47)
                        .addComponent(downb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startbActionPerformed

    private void downbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downbActionPerformed

    private void startbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startbMouseClicked
        int[][] target = new int [3][3], start = new int[3][3];
        start[0][0] = 8;
        start[0][1] = 1;
        start[0][2] = 4;
        start[1][0] = 5;
        start[1][1] = 7;
        start[1][2] = 3;
        start[2][0] = 6;
        start[2][1] = 2;
        start[2][2] = 0;
        target[0][0] = 0;
        target[0][1] = 1;
        target[0][2] = 2;
        target[1][0] = 3;
        target[1][1] = 4;
        target[1][2] = 5;
        target[2][0] = 6;
        target[2][1] = 7;
        target[2][2] = 8;
        puz = new Puzzle(3,3,target,start);
        downb.setEnabled(true);
        upb.setEnabled(true);
        leftb.setEnabled(true);
        rightb.setEnabled(true);
        endb.setEnabled(true);
        startb.setEnabled(false);
        sl00.setText(Integer.toString(puz.getstart()[0][0]));
        sl01.setText(Integer.toString(puz.getstart()[0][1]));
        sl02.setText(Integer.toString(puz.getstart()[0][2]));
        sl10.setText(Integer.toString(puz.getstart()[1][0]));
        sl11.setText(Integer.toString(puz.getstart()[1][1]));
        sl12.setText(Integer.toString(puz.getstart()[1][2]));
        sl20.setText(Integer.toString(puz.getstart()[2][0]));
        sl21.setText(Integer.toString(puz.getstart()[2][1]));
        sl22.setText(Integer.toString(puz.getstart()[2][2]));
        
        tl00.setText(Integer.toString(puz.gettarget()[0][0]));
        tl01.setText(Integer.toString(puz.gettarget()[0][1]));
        tl02.setText(Integer.toString(puz.gettarget()[0][2]));
        tl10.setText(Integer.toString(puz.gettarget()[1][0]));
        tl11.setText(Integer.toString(puz.gettarget()[1][1]));
        tl12.setText(Integer.toString(puz.gettarget()[1][2]));
        tl20.setText(Integer.toString(puz.gettarget()[2][0]));
        tl21.setText(Integer.toString(puz.gettarget()[2][1]));
        tl22.setText(Integer.toString(puz.gettarget()[2][2]));
        
    }//GEN-LAST:event_startbMouseClicked

    private void endbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endbMouseClicked
        downb.setEnabled(false);
        upb.setEnabled(false);
        leftb.setEnabled(false);
        rightb.setEnabled(false);
        endb.setEnabled(false);
        startb.setEnabled(true);
        sl00.setText("0");
        sl01.setText("0");
        sl02.setText("0");
        sl10.setText("0");
        sl11.setText("0");
        sl12.setText("0");
        sl20.setText("0");
        sl21.setText("0");
        sl22.setText("0");

        tl00.setText("0");
        tl01.setText("0");
        tl02.setText("0");
        tl10.setText("0");
        tl11.setText("0");
        tl12.setText("0");
        tl20.setText("0");
        tl21.setText("0");
        tl22.setText("0");
    }//GEN-LAST:event_endbMouseClicked

    private void upbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upbMouseClicked
        puz.up();
        sl00.setText(Integer.toString(puz.getprocess()[0][0]));
        sl01.setText(Integer.toString(puz.getprocess()[0][1]));
        sl02.setText(Integer.toString(puz.getprocess()[0][2]));
        sl10.setText(Integer.toString(puz.getprocess()[1][0]));
        sl11.setText(Integer.toString(puz.getprocess()[1][1]));
        sl12.setText(Integer.toString(puz.getprocess()[1][2]));
        sl20.setText(Integer.toString(puz.getprocess()[2][0]));
        sl21.setText(Integer.toString(puz.getprocess()[2][1]));
        sl22.setText(Integer.toString(puz.getprocess()[2][2]));
        check();
    }//GEN-LAST:event_upbMouseClicked

    private void downbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downbMouseClicked
        puz.down();
        sl00.setText(Integer.toString(puz.getprocess()[0][0]));
        sl01.setText(Integer.toString(puz.getprocess()[0][1]));
        sl02.setText(Integer.toString(puz.getprocess()[0][2]));
        sl10.setText(Integer.toString(puz.getprocess()[1][0]));
        sl11.setText(Integer.toString(puz.getprocess()[1][1]));
        sl12.setText(Integer.toString(puz.getprocess()[1][2]));
        sl20.setText(Integer.toString(puz.getprocess()[2][0]));
        sl21.setText(Integer.toString(puz.getprocess()[2][1]));
        sl22.setText(Integer.toString(puz.getprocess()[2][2]));
        check();
    }//GEN-LAST:event_downbMouseClicked

    private void rightbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightbMouseClicked
        puz.right();
        sl00.setText(Integer.toString(puz.getprocess()[0][0]));
        sl01.setText(Integer.toString(puz.getprocess()[0][1]));
        sl02.setText(Integer.toString(puz.getprocess()[0][2]));
        sl10.setText(Integer.toString(puz.getprocess()[1][0]));
        sl11.setText(Integer.toString(puz.getprocess()[1][1]));
        sl12.setText(Integer.toString(puz.getprocess()[1][2]));
        sl20.setText(Integer.toString(puz.getprocess()[2][0]));
        sl21.setText(Integer.toString(puz.getprocess()[2][1]));
        sl22.setText(Integer.toString(puz.getprocess()[2][2]));
        check();
    }//GEN-LAST:event_rightbMouseClicked

    private void leftbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftbMouseClicked
        puz.left();
        sl00.setText(Integer.toString(puz.getprocess()[0][0]));
        sl01.setText(Integer.toString(puz.getprocess()[0][1]));
        sl02.setText(Integer.toString(puz.getprocess()[0][2]));
        sl10.setText(Integer.toString(puz.getprocess()[1][0]));
        sl11.setText(Integer.toString(puz.getprocess()[1][1]));
        sl12.setText(Integer.toString(puz.getprocess()[1][2]));
        sl20.setText(Integer.toString(puz.getprocess()[2][0]));
        sl21.setText(Integer.toString(puz.getprocess()[2][1]));
        sl22.setText(Integer.toString(puz.getprocess()[2][2]));
        check();
    }//GEN-LAST:event_leftbMouseClicked
    
    private void check(){
        if (puz.finish()){
            downb.setEnabled(false);
            upb.setEnabled(false);
            leftb.setEnabled(false);
            rightb.setEnabled(false);
            endb.setEnabled(false);
            startb.setEnabled(true);
            sl00.setText("0");
            sl01.setText("0");
            sl02.setText("0");
            sl10.setText("0");
            sl11.setText("0");
            sl12.setText("0");
            sl20.setText("0");
            sl21.setText("0");
            sl22.setText("0");

            tl00.setText("0");
            tl01.setText("0");
            tl02.setText("0");
            tl10.setText("0");
            tl11.setText("0");
            tl12.setText("0");
            tl20.setText("0");
            tl21.setText("0");
            tl22.setText("0");
        }
    }
       
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton downb;
    private javax.swing.JButton endb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton leftb;
    private javax.swing.JButton rightb;
    private javax.swing.JLabel sl00;
    private javax.swing.JLabel sl01;
    private javax.swing.JLabel sl02;
    private javax.swing.JLabel sl10;
    private javax.swing.JLabel sl11;
    private javax.swing.JLabel sl12;
    private javax.swing.JLabel sl20;
    private javax.swing.JLabel sl21;
    private javax.swing.JLabel sl22;
    private javax.swing.JButton startb;
    private javax.swing.JLabel tl00;
    private javax.swing.JLabel tl01;
    private javax.swing.JLabel tl02;
    private javax.swing.JLabel tl10;
    private javax.swing.JLabel tl11;
    private javax.swing.JLabel tl12;
    private javax.swing.JLabel tl20;
    private javax.swing.JLabel tl21;
    private javax.swing.JLabel tl22;
    private javax.swing.JButton upb;
    // End of variables declaration//GEN-END:variables
}
